export enum PurchaseStatus {
  REQUESTED = 'REQUESTED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
}
